name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        django:
          - "3.2.23"
          - "4.2.9"
          - "5.0.1"
          - "6.0"
        drf:
          - "no"
          - "3.14.0"
        exclude:
          - python: "3.8"
            django: "5.0.1"
          - python: "3.8"
            django: "6.0"
          - python: "3.9"
            django: "5.0.1"
          - python: "3.9"
            django: "6.0"
          - python: "3.10"
            django: "6.0"
          - python: "3.11"
            django: "6.0"
          - python: "3.12"
            django: "3.2.23"
          - python: "3.12"
            django: "6.0"

    name: "Python ${{ matrix.python }} - Django ${{ matrix.django }} - DRF ${{ matrix.drf }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          pip install -r ci/requirements.txt
          if [[ "$DJANGO_VERSION" == "6.0" ]]; then
            pip install --upgrade --pre "Django>=$DJANGO_VERSION,<7.0"
          else
            pip install --upgrade "Django==$DJANGO_VERSION"
          fi
          if [[ "$DRF_VERSION" != "no" ]]; then pip install --upgrade djangorestframework==${DRF_VERSION}; fi
        env:
          DJANGO_VERSION: ${{ matrix.django }}
          DRF_VERSION: ${{ matrix.drf }}
      - name: Run Tests
        run: python runtests.py
